apiVersion: batch/v1
kind: Job
metadata:
  name: p1
spec:
  template:
    spec:
      containers:
      - name: p1
        image: perl
        # we'll use a perl image to calculate the value of pi to 1000 place
        command: ["perl", "-Mbignum=bpi", '-wle', "print bpi(1000)"]
      restartPolicy: Never
  backoffLimit: 3